version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=<username>
      - MONGO_INITDB_ROOT_PASSWORD=<password>
    volumes:
      - ./mongo-keyfile:/data/configdb/mongo-keyfile
    command: ["mongod", "--replSet", "rs0", "--bind_ip", "0.0.0.0", "--keyFile", "/data/configdb/mongo-keyfile"]

  mongo2:
    image: mongo:latest
    container_name: mongo2
    hostname: mongo2
    restart: always
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=<username>
      - MONGO_INITDB_ROOT_PASSWORD=<password>
    volumes:
      - ./mongo-keyfile:/data/configdb/mongo-keyfile
    command: ["mongod", "--replSet", "rs0", "--bind_ip", "0.0.0.0", "--keyFile", "/data/configdb/mongo-keyfile"]

  mongo3:
    image: mongo:latest
    container_name: mongo3
    hostname: mongo3
    restart: always
    ports:
      - 27019:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=<username>
      - MONGO_INITDB_ROOT_PASSWORD=<password>
    volumes:
      - ./mongo-keyfile:/data/configdb/mongo-keyfile
    command: ["mongod", "--replSet", "rs0", "--bind_ip", "0.0.0.0", "--keyFile", "/data/configdb/mongo-keyfile"]

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
     - 8081:8081
    restart: always
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=<username>
     - ME_CONFIG_MONGODB_ADMINPASSWORD=<password>
       #- ME_CONFIG_MONGODB_SERVER=localhost
     - ME_CONFIG_MONGODB_URL=mongodb://<username>:<password>@mongo:27017/
     - ME_CONFIG_MONGODB_REPLSETNAME=rs0
    depends_on:
     - mongo
     - mongo2
     - mongo3

networks:
  default:
    name: mongo-replica-set

volumes:
  mongo-keyfile:
    driver: local
    driver_opts:
      type: none
      device: ./mongo-keyfile
      o: bind
